### ISSUE TITLE
Please add support for files drag and drop

### ISSUE THREAD

**Issue by Davixk** [rossrobino/md#1]
Been loving this web app, but a very important feature in my workflow would be being able to easily drag and drop markdown files to the app window and have the file be automatically opened, instead of having to click on the open button and navigating to it manually from the popup file picker.

**Comment by rossrobino** [comment]
Sounds good to me, I added it in, let me know if that works. 

It will only work on chromium browsers that support the file system API (chrome, edge, arc...). Files from VS Code are dropped as strings with the path instead of files so I couldn't get it working directly from there. But it works using Finder/File Explorer or from the desktop.

**Comment by Davixk** [comment]
That was quick! Works great on my end (Chrome 117, Windows 11 22H2, drag & drop from Explorer).
Thank you

**Comment by rossrobino** [comment]
Great, thanks for the idea
